name: Refresh README cards

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

concurrency:
  group: refresh-readme
  cancel-in-progress: false

jobs:
  bump-version-param:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate version (UTC timestamp)
        id: gen
        run: echo "V=$(date -u +%Y%m%d%H%M)" >> $GITHUB_OUTPUT

      - name: Replace &v= in README.md
        run: |
          TS="${{ steps.gen.outputs.V }}"
          # Reemplaza cualquier &v=NUMEROS por &v=<timestamp> en README.md
          sed -E -i "s/(&v=)[0-9]+/\1${TS}/g" README.md
          echo "Preview of changes:"
          git --no-pager diff -- README.md || true

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain README.md)" ]]; then
            git config user.name  "readme-bot[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "🤖 chore(readme): bump cards cache v to ${{ steps.gen.outputs.V }}"
            git push
          else
            echo "No changes to commit."
          fi
